#配置端口号
server:
  port: 8888
  servlet:
    context-path: /sell


#配置数据源 druid
spring:
 druid:
   # url: jdbc:mysql:///mybase?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
   url: jdbc:mysql://192.168.1.177:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
   #driverClassName: com.mysql.jdbc.Driver
   username: root
   password: 123456
   maxActive: 30 #最大链接数
   maxWait: 10000 #获得链接的最大等待时间
 jackson:
   date-format: yyyy-MM-dd HH:mm:ss      #日期格式化
   default-property-inclusion: non_null  #返回json时忽略null值

jpa:
   show-sql: true  #显示sql语句

wechat:
   appid: wxcec0b9e65c084712
   secret: 05a7e861c1985ced86af77fb8f7163bc
   mchId: 1529533061
   mchKey: qwertyuiopasdfghjklzxcvbnm123456
   openid: oXDaO1RMGiRJACn5Bsp0nkHEqQ_w
   keyPath: G:\Xmcc\Frame\wechat_pay\src\main\resources\static\apiclient_cert.p12
   notifyUrl: http://xmcc-zhangkun.natapp1.cc/sell/pay/test




